defaults: &defaults
  docker:
    - image: cimg/node:16.15.0

version: 2.1

jobs:
  lint_and_unit_tests:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - cache-{{ .Branch }}-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - cache-
      - run: yarn install --frozen-lockfile
      - save_cache:
          key: cache-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - node_modules
            - ~/.npm
            - ~/.cache
      - run:
          command: yarn lint
      - run:
          command: yarn test
          environment:
            JEST_JUNIT_OUTPUT: "test-reports/jest-junit.xml"
      - store_test_results:
          path: test-reports

      - store_artifacts:
          path: test-reports
      
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - cache-{{ .Branch }}-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - cache-
      - run: yarn install --frozen-lockfile
      - save_cache:
          key: cache-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - node_modules
            - ~/.npm
            - ~/.cache
      - run:
          command: yarn build

workflows:
  version: 2
  ut_and_build:
    jobs:
      - lint_and_unit_tests
      - build:
          requires:
            - lint_and_unit_tests
